### ISSUE TITLE
第二个时钟提醒未到时间久弹出提醒

### ISSUE THREAD

**Issue by lushan2866** [IAliceBobI/sy-plugins#1]
如题所示。
![image](https://github.com/IAliceBobI/sy-plugins/assets/5708881/d92302a6-81b6-4281-8dc4-0dc05b062bf4)

**Comment by IAliceBobI** [comment]
@lushan2866 您好，感谢反馈。我测试了几次，没有复现。 不知道您那边是否能复现？

**Comment by lushan2866** [comment]
不好意思，暂时移出了此插件。
在群里和群友讨论后，怀疑是改了块和标签的时间后。好像块和这个弹窗的LInk 断开了，所以一直提醒。

**Comment by IAliceBobI** [comment]
@lushan2866 
多谢反馈，我再检查一下。
那个弹窗会去找之前的块id，存在就弹窗，不然就不弹窗。弹窗时也会删除任务。大概就是这样的简单逻辑。
再次感谢！
