### ISSUE TITLE
按标点断句（包括形成任务列表和形成列表）未兼容带链接的文本块

### ISSUE THREAD

**Issue by lightXXu** [IAliceBobI/sy-plugins#11]
在试用插件的过程中，发现无法兼容带链接的文本。以下面文字为例

<details><summary>测试文本点我展开</summary>
<p>

对于学习材料的整体印象的建立并不需要考虑到细枝末节处。恰恰相反，该印象越简单越好，我们的学习材料的基础章节也是越短越好。越是简单的知识模型越是容易被理解。日后我们可以在此基础上进一步构建。不要忽视基础。记忆看似浅显的知识并不是在浪费时间。基础知识可能会突然变动(有些教材在使用概念时喜欢在开头规定限定条件，或者把一些术语简写)，而且记忆简单的知识所花费的时间也不多，所以还是保险一点好。要知道，通常我们会花费 50% 的时间来复习学过的材料中的 3% - 5% 【[[来源](https://link.zhihu.com/?target=https%3A//www.supermemo.com/articles/theory.htm)](https://link.zhihu.com/?target=https%3A//www.supermemo.com/articles/theory.htm)】。基础知识只要花很少时间就能记住。然而，对基础知识的疏忽往往代价沉重（一个简单而根深蒂固的概错误概念很可能害我们自己白白浪费了学习后续章节的时间）。

</p>
</details> 
<br></br>

**以上文本实际按标点断句的结果如下所示，大部分都没有正常断句。**
<img width="1316" alt="image" src="https://github.com/IAliceBobI/sy-plugins/assets/20875795/e9e5c281-9076-4f98-8525-cdc554277813">

**删除链接后，按标点断句如下所示，符合预期。**
![image](https://github.com/IAliceBobI/sy-plugins/assets/20875795/e23cf7b6-c097-4e4d-9758-702701360aa5)

**Comment by IAliceBobI** [comment]
目前的处理逻辑比较简单。图个快速开发。后续再慢慢优化。感谢反馈。

**Comment by IAliceBobI** [comment]
@lightXXu 

https://github.com/IAliceBobI/sy-progressive-plugin/releases/tag/v0.16.4

目前改进了一下。如果有链接，也能拆分，就是拆分后，不带链接了。
