### ISSUE TITLE
在Dailynote中新的闪念添加至页面最前端

### ISSUE THREAD

**Issue by 5kyfkr** [IAliceBobI/sy-plugins#14]
https://github.com/suka233/siyuan-knote/issues/10
https://github.com/siyuan-note/siyuan/issues/11442
大佬如上面两个issue，现在有api可以从日记头部添加新的记录，希望能增加选项切换设置

**Comment by IAliceBobI** [comment]
更新了，麻烦一会儿试试。  @5kyfkr

**Comment by 5kyfkr** [comment]
> 更新了，麻烦一会儿试试。 @5kyfkr

好滴，大佬神速，等下试试。另外有没有考虑桌面端弄个全局快捷键的弹窗输入，像knote一样，现在藏在侧栏里感觉有时还是没快捷键打开日记后输入快

**Comment by IAliceBobI** [comment]
主要是想给手机用的。

不过这想法不错，我一会儿想想。

**Comment by 5kyfkr** [comment]
还有大佬就是如下图，字体感觉有点大，输入框应该可以再高一点
![Screenshot_20240522_122704_org b3log siyuan](https://github.com/IAliceBobI/sy-plugins/assets/63196026/aa6bfeeb-77ce-4df6-86f5-ce3576d9723c)

**Comment by 5kyfkr** [comment]
![image](https://github.com/IAliceBobI/sy-plugins/assets/63196026/80d5c02e-89f1-4f6f-bd69-0324eac22205)
前端插入试了很好用，感谢大佬
另外日期信息感觉没必要显示到后面，因为都是在对应当天的日记里面，有点重复了。
还有个疑问就是只要交替同步应该不会出现同步冲突吧，我反正养成习惯是交替同步的，不会同时编辑两端。

**Comment by IAliceBobI** [comment]
@5kyfkr 交替的话没事，我以前都是这样做的。但如果没冲突的话，能同时用两个端，效率更高。 手机随时输入，比如拍照。

桌面端持续编辑。

**Comment by IAliceBobI** [comment]
@5kyfkr  如果手机端插入的内容没及时同步到桌面端，比如间隔几天，当同步时，会写入当天的日记。所以这个时间是有用的。

如果不开启冲突规避，可以考虑不加入时间。

**Comment by 5kyfkr** [comment]
> 如果不开启冲突规避，可以考虑不加入时间。

这个可以，我就没开规避，同时编辑同时拍照这场景对我来说用不到，有多屏协同那些功能够方便把手机相片拖到电脑里了

**Comment by IAliceBobI** [comment]
@5kyfkr 输入框会自动扩大的。字体可以小点。

**Comment by 5kyfkr** [comment]
> @5kyfkr 输入框会自动扩大的。字体可以小点。

可以滴，字小点就完美了，20px左右应该够了

**Comment by IAliceBobI** [comment]
https://gitee.com/TokenzQdBN/sy-plugins/blob/main/sy-tomato-plugin/README_zh_CN.md#%E6%8B%8D%E7%85%A7%E9%97%AA%E5%BF%B5

@5kyfkr 

![image](https://github.com/IAliceBobI/sy-plugins/assets/3294007/a1ac1fe7-b2a4-474c-811b-5d40eba079cc)

**Comment by 5kyfkr** [comment]
> https://gitee.com/TokenzQdBN/sy-plugins/blob/main/sy-tomato-plugin/README_zh_CN.md#%E6%8B%8D%E7%85%A7%E9%97%AA%E5%BF%B5
> 
> @5kyfkr
> 
> ![image](https://private-user-images.githubusercontent.com/3294007/332871480-a1ac1fe7-b2a4-474c-811b-5d40eba079cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzOTQwMzMsIm5iZiI6MTcxNjM5MzczMywicGF0aCI6Ii8zMjk0MDA3LzMzMjg3MTQ4MC1hMWFjMWZlNy1iMmE0LTQ3NGMtODExYi01ZDQwZWJhMDc5Y2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjJUMTYwMjEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmMwODlhY2MwMDZiNzI0ODUwMDlmNzNjMGI3N2Q0YWUxOGM1ZWIwNGFmM2E1YmQ0NzBkYjk2NmMwNDFlMzNiYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5IR_JNScM3vVBlScJ3VMsvWGuwTKdVts_RTHo56CjSw)

6，敏捷开发之神

**Comment by 5kyfkr** [comment]
@IAliceBobI 大佬，我试了快捷键ctrl+Q是思源的窗口上再叠加一个快捷添加窗口，有没可能只是单独中间的界面在外显示？不整个把思源也弹窗出来
![image](https://github.com/IAliceBobI/sy-plugins/assets/63196026/7053cb18-6b20-40b7-83db-a0df617472e8)
另外ctrl+alt+z好像没效果，不过感觉有ctrl+Q就够了

**Comment by IAliceBobI** [comment]
ctrl+alt+z 需要自己手动删除再设置上。可能思源有bug。侧边栏取消了，只有移动端有。ctrl+Q的我改为弹出窗口看看吧。

**Comment by 5kyfkr** [comment]
> ctrl+alt+z 需要自己手动删除再设置上。可能思源有bug。侧边栏取消了，只有移动端有。ctrl+Q的我改为弹出窗口看看吧。

好的，试了ctrl+alt+z 重加好了，ctrl q和ctrl+alt+z逻辑应该保证有一个全局的就行，ctrl+alt+z除了日记不会弹出来没有什么区，把全局优化好合并成一个ctrl+q快捷键应该就够了

**Comment by 5kyfkr** [comment]
还有两点如果有余力也能做一下。。。
- 输入界面置顶
- 支持切换为思源编辑器，可以方便粘贴图片

![image](https://github.com/IAliceBobI/sy-plugins/assets/63196026/80de9d13-2f29-47ed-a05a-5225db736085)

**Comment by 5kyfkr** [comment]
knote大佬我中午催了他一下把顶部添加也弄出来了，后面那两个有余力的可以不弄了，桌面端我还是用knote够了，移动端传图片用大佬的会比knote快

**Comment by IAliceBobI** [comment]
ok，不过我搞来自用了。 基本搞好了，除了编辑器切换，还有几个类别的持久化。后续慢慢搞。

**Comment by IAliceBobI** [comment]
搞这个主要是，不想开服务器。  我只需要电脑与手机通过 oss 同步就好。

手机与电脑一直开着，随时等着输入。

控制只开一个端比较麻烦，在做这个功能前我就是这样干的。 
这个功能就让两个端同时输入，不浪费一点灵感。

**Comment by 5kyfkr** [comment]
> 搞这个主要是，不想开服务器。 我只需要电脑与手机通过 oss 同步就好。
> 
> 手机与电脑一直开着，随时等着输入。
> 
> 控制只开一个端比较麻烦，在做这个功能前我就是这样干的。 这个功能就让两个端同时输入，不浪费一点灵感。

双端同时开始用还是比较担心哪次编辑忘了同步，如果只编辑日记和新增加文档防止冲突应该问题不大，就是怕又操作了其他文档，总体还是交替同步放心点，一般有电脑的地方也就用电脑，两端一起用的场景我还是比较少，同步问题确实是思源最难绷的地方

**Comment by IAliceBobI** [comment]
@5kyfkr 手机端开30s无改变自动同步就好。手机部分，我就是当作刷卡用，与随时记录用。

**Comment by 5kyfkr** [comment]
> @5kyfkr 手机端开30s无改变自动同步就好。手机部分，我就是当作刷卡用，与随时记录用。

是滴，自动同步没什么问题，就是要确保30s内不要在电脑编辑搞混了

**Comment by 5kyfkr** [comment]
试了下新版，好像加载小窗有点慢，要两三秒，窗口位置好像也动不了

**Comment by IAliceBobI** [comment]
我这里是1秒

**Comment by IAliceBobI** [comment]
![image](https://github.com/IAliceBobI/sy-plugins/assets/3294007/6407f565-4bca-4e96-a8aa-a8ece002a02f)
目前用的是这个方式打开的。这个方式确实性能差点。

**Comment by 5kyfkr** [comment]
https://github.com/IAliceBobI/sy-plugins/assets/63196026/40ba19d7-833a-4dce-9d2d-95396080e511

我这用默认主题也拖不动，打开3秒

**Comment by IAliceBobI** [comment]
是v0.23.19吗?


https://github.com/IAliceBobI/sy-plugins/assets/3294007/9425ddd6-4a65-4b89-a1eb-36287cd1ab04

**Comment by 5kyfkr** [comment]
是v0.23.19，关了css和js也一样

**Comment by IAliceBobI** [comment]
我这前端技术是业余的。我先关闭了。有问题再开。多谢反馈。
