### ISSUE TITLE
关于将dailynote加入分片阅读时遇到的困难

### ISSUE THREAD

**Issue by pureTrue** [IAliceBobI/sy-plugins#15]
问题1：dailynote双链的公认用法：主要依靠传递型双链、关联型双链来将子节点内容聚合在反链面板当中。但是一旦纳入分片阅读，分片文档会复刻源文档的排版，导致每个双链会传递两份同样的内容给反链面板，反链面板可用性减半。

解决方法：创建分片文档后，自动将分片内的「引用」转换为「链接」；期望渐进学习插件能内置该功能，否则自己手动转换体验太差

---

问题2：现在的渐进学习插件仅为线性文本（也就是文章）做了优化，对大纲、无序列表优化较差。文章分片会在每个块末尾创建一个「`*`原文链接」，而大纲分片则仅在最后一个子块末尾有一个`*`。

解决方法：每个大纲块的末尾都创建一个原文引用

---

问题3：大纲列表使用`Alt+E`进行挖空制卡时，cards-文档仅摘录当前块中的内容，完全丢失了上下文的面包屑，导致闪卡复习时记忆提取困难。
    这个问题最严重，直接导致了dailynote践行渐进学习的不可用，前两个问题还可以忍受（或直接在原dailynote中进行alt+E摘录，省去分片阅读步骤）

解决方法：如果技术上可行，可以在cards-文档的每张摘录闪卡的上方黄色标题屑`list::before`的后面，再多添加摘录块的面包屑作为上下文提示。

@IAliceBobI

**Comment by IAliceBobI** [comment]
问题3的列表路径是我特意忽略的。主要是太长了。我给你加上先吧。 @pureTrue

**Comment by pureTrue** [comment]
感谢，我这边用dailynote一来大纲层级不会太深，面包屑长度就没那么严重；二来我自己也用CSS将面包屑字体大小调整过了，面积占比也感觉还可以。

关键我这种用法，正文很短，往往摘录块内就几个关键词，所以就需要比较完整的面包屑来辅助。

另外如果有人觉得长，面包屑也可以只保留往上3-4层级我也觉得足够了。

---

另外我讲一下我的用法吧，希望给老哥后续开发带来点灵感：

每天dailynote输入内容，每个传递型双链作为父节点，独占一个「容器块」——方便渐进学习插件按块数1拆分。

这样，每次用插件开始学习，一页就是一个完整独立的主题。

多数时间，我都在记录「结构型笔记」，类似思维导图，主要通过知识结构来串联知识点，每个节点1个关键词。（这一类非常需要完整的面包屑）

如果要学习知识结构下的细分知识点，我才会抛开结构，用大段的文字论证，这时候的大纲主要表现的是文本的递进、转折、主次。（这一类只需要往上1层的面包屑）

其实对于结构笔记，*同一层级的“上下文”*也很重要，这表明了本块在其父节点下的位置/排序，只是现在好像所有的大纲笔记都没有给这种用法做支撑。思源中如何解决我也没有什么思路…

**Comment by IAliceBobI** [comment]
非常感谢分享。

一会儿试试  https://github.com/IAliceBobI/sy-progressive-plugin/releases/tag/v0.16.6

**Comment by IAliceBobI** [comment]
@pureTrue 集市安装就好。又发了一版，刚才那个版本好像没用上新代码。再次感谢你分享的用法。有问题再开。

**Comment by IAliceBobI** [comment]
> 其实对于结构笔记，*同一层级的“上下文”*也很重要，这表明了本块在其父节点下的位置/排序，只是现在好像所有的大纲笔记都没有给这种用法做支撑。思源中如何解决我也没有什么思路…

@pureTrue  看看这个方案如何，[同一层](https://gitee.com/TokenzQdBN/sy-plugins/blob/main/sy-tomato-plugin/README_zh_CN.md#%E6%A6%82%E5%BF%B5%E6%A0%8F%E5%BC%95%E7%94%A8%E6%A0%8F)级也能关联上。
