### ISSUE TITLE
应该是删除图标在前，跑路图标在后

### ISSUE THREAD

**Issue by tcmtom** [IAliceBobI/sy-plugins#2]
![image](https://github.com/IAliceBobI/sy-plugins/assets/94541098/68499624-0c56-4f87-804c-3a59dcc13c25)

**Comment by IAliceBobI** [comment]
放前面，小人被垃圾桶挡住，跑不了。

**Comment by IAliceBobI** [comment]
ok， 请关注集市下载新版。

**Comment by IAliceBobI** [comment]
@tcmtom https://github.com/IAliceBobI/sy-progressive-plugin/releases/tag/v0.14.30
