### ISSUE TITLE
标点断句时会把markdown代码引用的图片打断

### ISSUE THREAD

**Issue by nightlye** [IAliceBobI/sy-plugins#4]
如题，有些图片以markdown代码形式引用，网页图片通常会带有符号"."，因此会被打断从而取消了图片引用。这个问题只要是和网址有关都会出现，包括但不限于超链接、图片引用、网址。像这种情况应该如何处理呢？
例如原文：
<img width="678" alt="73e27ecf1a93855f26e0516c561cbf58" src="https://github.com/IAliceBobI/sy-plugins/assets/53067795/76c6087c-0eb1-4a96-9f46-992356efbc85">

打断后：
<img width="759" alt="ab9e010c3f241f00e45cc2e22c4b785f" src="https://github.com/IAliceBobI/sy-plugins/assets/53067795/c4d1eacb-a540-41c3-905b-26e8c857d0b0">

**Comment by IAliceBobI** [comment]
多谢反馈。我找个时间研究一些。

**Comment by IAliceBobI** [comment]
https://github.com/IAliceBobI/sy-progressive-plugin/releases/tag/v0.14.59

试试这个。有问题再开。
