### ISSUE TITLE
用本书闪卡按钮实现打开任意文档闪卡可行性

### ISSUE THREAD

**Issue by AvoidantPerDis** [IAliceBobI/sy-plugins#5]
如题，我替换了globalThis.progressive_zZmqus5PtYRi.progressive.htmlBlockReadNextPeice("20240307225416-x4f2607","20240327140620-fy9zpuv",12,5)中的第一个块ID实现了打开制定文档的闪卡，想问一下其他参数的作用
（本来想问能不能改为全屏闪卡，后来发现退出不方便）

**Comment by AvoidantPerDis** [comment]
不过手机点击一直提示等待索引建立

**Comment by IAliceBobI** [comment]
https://github.com/IAliceBobI/sy-plugins/blob/3e69097a6dfb8fc8b5c846c8e9db68d43107b77a/sy-progressive-plugin/src/Progressive.ts#L431

https://github.com/IAliceBobI/sy-plugins/blob/000434021b6a1e951b8f93f7e715dda888f9e234/sy-progressive-plugin/src/constants.ts#L8

**Comment by IAliceBobI** [comment]
```
            case HtmlCBType.openFlashcardTab:
                if (bookID) openTab({ app: this.plugin.app, card: { type: "doc", id: bookID } });
                else openTab({ app: this.plugin.app, card: { type: "all" } });
                break;
```

你传入书籍ID就可以了。

globalThis.progressive_zZmqus5PtYRi.progressive.htmlBlockReadNextPeice("书籍","",12, 0)

**Comment by AvoidantPerDis** [comment]
那我试试

**Comment by AvoidantPerDis** [comment]
@IAliceBobI 手机伺服浏览器端可以打开，移动端闪卡界面调不出来，是官方的限制吗？

**Comment by AvoidantPerDis** [comment]
另外就是，这个按钮可以不依赖插件实现吗

**Comment by IAliceBobI** [comment]
理论上可以。没研究过。你可以开发一个插件，使用思源提供的插件api openTab打开。

**Comment by IAliceBobI** [comment]
> @IAliceBobI 手机伺服浏览器端可以打开，移动端闪卡界面调不出来，是官方的限制吗？一直显示等待索引，要么就是没反应，有解决办法吗

手机上的接口功能不全。

**Comment by AvoidantPerDis** [comment]
> > @IAliceBobI 手机伺服浏览器端可以打开，移动端闪卡界面调不出来，是官方的限制吗？一直显示等待索引，要么就是没反应，有解决办法吗
> 
> 手机上的接口功能不全。

那插件自己的功能能用吗

**Comment by IAliceBobI** [comment]
> > > @IAliceBobI 手机伺服浏览器端可以打开，移动端闪卡界面调不出来，是官方的限制吗？一直显示等待索引，要么就是没反应，有解决办法吗
> > 
> > 
> > 手机上的接口功能不全。
> 
> 那渐进学习插件自己的功能能用吗



就是用的官方的接口。在pc端可以，手机端不行。

**Comment by AvoidantPerDis** [comment]
> > > > @IAliceBobI 手机伺服浏览器端可以打开，移动端闪卡界面调不出来，是官方的限制吗？一直显示等待索引，要么就是没反应，有解决办法吗
> > > 
> > > 
> > > 手机上的接口功能不全。
> > 
> > 那渐进学习插件自己的功能能用吗
> 
> 
> 
> 就是用的官方的接口。在pc端可以，手机端不行。

那需不需要提个issue，不然除了伺服移动端都没法用，本来使用场景应该很适合手机的

**Comment by IAliceBobI** [comment]
> > > > > @IAliceBobI 手机伺服浏览器端可以打开，移动端闪卡界面调不出来，是官方的限制吗？一直显示等待索引，要么就是没反应，有解决办法吗
> > > > 
> > > > 
> > > > 手机上的接口功能不全。
> > > 
> > > 
> > > 那渐进学习插件自己的功能能用吗
> > 
> > 
> > 就是用的官方的接口。在pc端可以，手机端不行。
> 
> 那需不需要提个issue，不然除了伺服移动端都没法用，本来使用场景应该很适合手机的

手机app要大改。等改了就好了。
