### ISSUE TITLE
闪卡复习不显示图片遮挡区

### ISSUE THREAD

**Issue by 5kyfkr** [IAliceBobI/sy-plugins#6]
![image](https://github.com/IAliceBobI/sy-plugins/assets/63196026/1900ccb0-368d-4807-9fba-fb0e98957781)
![image](https://github.com/IAliceBobI/sy-plugins/assets/63196026/51c59afe-c985-4e66-a73b-76ecda0e33fb)
如图，遮挡在闪卡中未显示

**Comment by IAliceBobI** [comment]
@5kyfkr 你好，感谢反馈。不过我这里测试了是正常的。

**Comment by 5kyfkr** [comment]
> @5kyfkr 你好，感谢反馈。不过我这里测试了是正常的。

3.0.6 dev2好像正常了。3.0.5不行，等下版本再看看

**Comment by 5kyfkr** [comment]
好像又好了，手机端3.05又正常了，能稳定复现再看，我先关了

**Comment by IAliceBobI** [comment]
感谢反馈，已经修复：https://github.com/IAliceBobI/sy-tomato-plugin/releases/tag/v0.20.8

**Comment by 5kyfkr** [comment]
> 感谢反馈，已经修复：https://github.com/IAliceBobI/sy-tomato-plugin/releases/tag/v0.20.8

6，神速
