### ISSUE TITLE
两个问题和需求

### ISSUE THREAD

**Issue by leeyaunlong** [IAliceBobI/sy-plugins#7]
能增加一个 交换引用和原文
比如 在文档 a 中有 一段内容 a1 , 在文档b中 有 a1的引用链接/嵌入引用 b1. 
能搞个功能出来 交换 a1 和b1吗?
就是让b,b1中存 真实的内容 , a.a1中引用  b1

另外 番茄的 全局定位按钮 快捷键是死的(alt+1) 实际不能修改. 
siyuan在文件树上本来就有一个定位按钮, 而番茄的定位按钮也不能调位置跟原生的定位基本都在一个位置.
番茄的能修改定位按钮的位置吗? 或者集成到页签?

**Comment by IAliceBobI** [comment]
alt+1可以改。官方的也是alt+1。得把官方的去掉，再改。

插件的alt+1功能与官方的不一样。    是先全部折叠在展开。

**Comment by IAliceBobI** [comment]
交换引用和原文。这个如果一个原文多个引用这么处理。

这个用什么场景吗，我目前还没用得到。

**Comment by leeyaunlong** [comment]
> 交换引用和原文。这个如果一个原文多个引用这么处理。
> 
> 这个用什么场景吗，我目前还没用得到。

只交换当前 触发位置的 这一个吧.

场景:
比如你要做某个project的研究, 比如 研究 chatgpt的向量化本地实现.
这种大项目肯定不是一天完成的, (所以放一个 prj_ai的文件里面每天加不现实, 肯定是每天再daliynote中 开个片段)
也可能有很多中间的弯路和分叉 可能一天有多个 摘录或者笔记片段.

然后定期做 review的时候, 可能吧 有效的内容, 通过你开发的 底部backlink的 移动功能直接移动到 prj_ai里面去了.
但可能有些不确定的 只加了个引用链接到 prj_ai中
之后可能觉得这些在 prj_ai中的引用有价值, 就会移动正文过来, ( 但这时候可能不想丢了 原来 day note中的结构 ,所以能反向吧 引用链接放在 daynote中就很有必要)
也有可能移动过来的内容是交叉的节点, 原来的位置肯定要留个锚点, 否则原来的笔记就支离破碎了.

**Comment by leeyaunlong** [comment]
> alt+1可以改。官方的也是alt+1。得把官方的去掉，再改。
> 
> 插件的alt+1功能与官方的不一样。 是先全部折叠在展开。
貌似是显示的问题,  已经快捷键改了(实际也改了), 但界面上还是现实alt+1, 
能让图标顶栏靠右显示吗?
![image](https://github.com/IAliceBobI/sy-plugins/assets/19405648/37c092e9-dd8c-46e8-b8be-29a6aacaeca3)

**Comment by IAliceBobI** [comment]
@leeyaunlong 那个是写死的。显示改不了。

靠右暂时不搞了。维护插件时间开销太大。

**Comment by leeyaunlong** [comment]
> @leeyaunlong 那个是写死的。显示改不了。
> 
> 靠右暂时不搞了。维护插件时间开销太大。

可以理解

**Comment by IAliceBobI** [comment]
> > 交换引用和原文。这个如果一个原文多个引用这么处理。
> > 这个用什么场景吗，我目前还没用得到。
> 
> 只交换当前 触发位置的 这一个吧.
> 
> 场景: 比如你要做某个project的研究, 比如 研究 chatgpt的向量化本地实现. 这种大项目肯定不是一天完成的, (所以放一个 prj_ai的文件里面每天加不现实, 肯定是每天再daliynote中 开个片段) 也可能有很多中间的弯路和分叉 可能一天有多个 摘录或者笔记片段.
> 
> 然后定期做 review的时候, 可能吧 有效的内容, 通过你开发的 底部backlink的 移动功能直接移动到 prj_ai里面去了. 但可能有些不确定的 只加了个引用链接到 prj_ai中 之后可能觉得这些在 prj_ai中的引用有价值, 就会移动正文过来, ( 但这时候可能不想丢了 原来 day note中的结构 ,所以能反向吧 引用链接放在 daynote中就很有必要) 也有可能移动过来的内容是交叉的节点, 原来的位置肯定要留个锚点, 否则原来的笔记就支离破碎了.


这需求可以放到复制功能里面。
复制的时候，给两边都加个链接。互相能链接过去。

**Comment by IAliceBobI** [comment]
https://github.com/IAliceBobI/sy-tomato-plugin/releases/tag/v0.20.50

可以试试这个。有问题再开。

**Comment by leeyaunlong** [comment]
> https://github.com/IAliceBobI/sy-tomato-plugin/releases/tag/v0.20.50
> 
> 可以试试这个。有问题再开。

厉害, 试了下初步可用.
