### ISSUE TITLE
禁用底部反链后，最后一行文本只能在最底部编辑

### ISSUE THREAD

**Issue by nuomici2222** [IAliceBobI/sy-plugins#9]
禁用底部反链后，最后一行文本只能在最底部编辑，一般来说文本应该可以在页面中部位置编辑（思源v3.0.12）
![image](https://github.com/IAliceBobI/sy-plugins/assets/94222529/dc8d27e9-9b5f-47a4-bd93-bd3650cedffe)

启用底部反链时的状态：
![image](https://github.com/IAliceBobI/sy-plugins/assets/94222529/4190ab39-a180-4ec7-9ab1-4ca635cd3855)

关闭反链功能时的状态：
![image](https://github.com/IAliceBobI/sy-plugins/assets/94222529/97248890-3f12-40df-8b36-aeb5d5d536e6)

**Comment by IAliceBobI** [comment]
https://github.com/IAliceBobI/sy-tomato-plugin/releases/tag/v0.20.59


试试这个。有问题再开。

**Comment by nuomici2222** [comment]
> https://github.com/IAliceBobI/sy-tomato-plugin/releases/tag/v0.20.59
> 
> 试试这个。有问题再开。

确实好了，感谢~
